superfly/fly-go

- flaps/flaps_machines.go
Flaps already accepts it, so allow this in the client.
This is gonna be used to cordon old machines during blue-green deployment
in an attempt to make zero downtime.
> Allow to pass a lease to cordon/uncordon calls

- machine_types.go
To be able to override the default secrets set on every machine in an app, we want to support machine specific secrets. To not break any backwards compatibility behavior, we'll limit the ability to use machine specific secrets to one that make use of processes. If a process contains at least one secret, the only secrets injected into the VM/process will be what has been explicitly provided.
> feat: expose the ability to set Machine specific secrets using processes

- machine_types.go
This is needed to support certain features in FKS.
> feat: exposes the ability to define env vars from certain machine fields

- machine_types.go
- machine_types_test.go
pass tests
```
fly-go on copy-gpu-count via 🐹 v1.22.0 took 2s
❯ go test .
ok      github.com/superfly/fly-go      (cached)
```
> Rightly (un)set GPU fields on MachineGuest.SetSize()

- machine_types.go
The option indicates that the proxy shouldn't add any fly-specific
headers to HTTP responses.
> Add 'pristine' boolean option to HTTPResponseOptions

- flaps/flaps.go
- flaps/flaps_error.go
We want to log the trace-id on errors so we can easily lookup the command on honeycomb
> Add trace-id to flaps error type

- machine_types.go
- volume_types.go
(After some discussion, we're renaming this before announcing it.)
> Rename `WorkerStatus` to `HostStatus`

- resource_ssh.go
Allow for long-lived certs when tied to a specific address.
> Allow source address to be specified when issuing ssh cert

- machine_types.go
- machine_types_test.go
This PR implements support for autosuspending Machines.
After discussion, we decided that the best way to configure autosuspend is through the existing Machine autostop field. Consequently, this introduces a textual representation for the field with three settings: "off", "stop", and "suspend".
To maintain backward compatibility for existing Machines API clients, JSON deserialization will continue to accept booleans, and JSON serialization will prefer the boolean representations for "off" and "stop".
When this change is incorporated into flyctl, `fly.toml` serialization will default to using the new textual representation. Deserialization will continue to accept booleans. Through a quirk of the parser, it will also accept the strings "false" and "true"; unfortunately, I don't think we'll …
> Add support for autosuspending Machines

- machine_types.go
After #80, the generated documentation shows the integer values of the constants for the `MachineAutostop` type. Fix this, document the meaning of the new options, and note that the old boolean format still works.
> Fix autostop field documentation

- flaps/flaps.go
- flaps/flaps_machines.go
- flaps/retry.go
Sending `^C` while trying to acquire a lease currently just hangs.
> Pass context into flaps Retry function so lease attempt can cancel

- machine_types.go
Will be used by FKS to set permissions for files in projected volumes.
> Allow to specify guest file permissions

- resource_apps.go
- types.go
Should this be an int32? The GraphQL API exposes an int for this value, but for the InternalNumericID of orgs, it's a BigInt.
Changing that would probably be a breaking API change though.
> Expose `InternalNumericID` for `App`

- machine_types.go
Will be used to tell the backend what kind of check a top-level check
is. With virtual services the checks are gonna be assigned per-machine
(top level) and not per service, yet we need checks that will force
a machine out of LB pool if they fail.
> Add optional 'kind' field to MachineCheck

- resource_apps.go
Return the shared IP address in the `App` object returned from `GetApp()`, which informs user of the public IP address of their app if they allocate a shared IP address (which is the default). This avoids the need to call `GetIPAddress()` explicitly.
> add shared ip address to graphql query of `GetApp()`

- resource_organizations.go
- resource_tokens.go
- types.go
We need `revokedAt` returned by the orgs query in order to be able to display revocation date when a user does `flyctl tokens ls --org ORG_NAME`.
Also changes the type of `RevokedAt` to a `*time.Time` instead of `time.Time`, so that nulls in the database are converted to `nil` in Go, rather than to the zero-value of a `time.Time`.
> Query revokedAt when grabbing orgs

- flaps/flaps.go
We have some components that don't return JSON. For fixing them, this change exposes the response body as is if a request is not JSON.
https://github.com/superfly/flyctl/actions/runs/11440424372/job/31826716962#step:7:47
```
Error: could not destroy machine 48e2d61c133e08: failed to destroy VM 48e2d61c133e08: request returned non-2xx status, 408 (Request ID: 01JAQJJE2YR2FZFSQX92BGK530-sjc)
```
> fix: don't discard a response body even if it isn't JSON

- flaps/retry.go
Before the change, AcquireLease() was blocking indefinitely if the machine's host was offline.
> fix: don't retry indefinitely

- machine_types.go
Not all of the `MachineCheck` fields are supported for service checks.
This PR improves our documentation by splitting these into separate structs.
> machine_types: Split MachineServiceCheck from MachineCheck

- flaps/actions.go
- flaps/flaps_platform.go
- flaps/flapsaction_string.go
- types.go
Adds a `capacity` field to the Regions struct, and a `GetRegions` client query that calls the `/platform/regions` API which populates this field.
See superfly/nomad-firecracker#3304 (internal) for further details.
> flaps client platform/regions API

- resource_organizations.go
I've discovered some places where we still receive "personal" but need the underlying slug
> include raw slug most of the time we get an organization

- .github/workflows/checks.yml
- .golangci.yml
- client.go
- flaps/flaps_machines.go
- go.mod
- resource_ip_addresses.go
1.21 is no longer supported by the Go team. This will unlock other updates such as https://github.com/superfly/fly-go/pull/166.
> build: upgrade Go from 1.21 to 1.24
