volume_types.go
The pull request hasn't been merged, but the backend is supporting the field already.
=> Add FSType again from https://github.com/superfly/flyctl/pull/2527

volume_types.go
Needed for https://github.com/superfly/flyctl/pull/3260
=> toggle scheduled snapshots

flaps/flaps_machines.go, fly.go
This PR removes some cruft that happened when we split `fly-go` from `flyctl`.
=> Fix metrics & MergeFiles()

machine_types.go
This is needed to make for https://github.com/superfly/flyctl/pull/2855
=> Restart policy becomes a pointer

resource_organizations.go
For https://github.com/superfly/flyctl/pull/3442
=> Fetch org internal id

tokens/tokens.go
I jumped the gun on merging https://github.com/superfly/fly-go/pull/34. For https://github.com/superfly/flyctl/pull/3442.
=> Accessors for working with tokens.Tokens concurrently

machine_types.go, volume_types.go
This was just added to the Machines API.
=> Add worker status fields for Machines and volumes

flaps/flaps.go
Add support for custom HTTP transports while constructing a `flaps.Client`. The same is already possible with `fly.Client`, through `fly.ClientOptions`.
=> flaps: add support for custom HTTP transports

resource_volumes.go, volume_types.go
This depends on the api update, which has not been quite completed yet.
=> Add retention days to volume snapshots

resource_remote_builders.go, types.go
This helped unblock users that have problems pushing images from one region to the registry
https://community.fly.io/t/machines-wont-start/19732/54
=> Support parameter to override builder region

resource_apps.go, tokens/tokens.go, types.go
Needed for some token work in `flyctl`
=> Add InternalNumericID to OrganizationBasic, export tokens.StripAuthorizationScheme

machine_types.go
Add hostname and hostname fqdn options to machines so we can configure them. used for FKS
=> add hostname to machine type

resource_ip_addresses.go, types.go
Required for https://github.com/superfly/flyctl/pull/3279
=> Add fields for virtual services

resource_apps.go
I didn't want to create a new graphql query so I did the easiest thing possible.
=> Add get fly-deployer method flaps client

machine_types.go
Related to https://github.com/superfly/flyctl/pull/3745
=> Add spot-price restart policy for gpu machines

resource_apps.go, types.go
Supercedes https://github.com/superfly/fly-go/pull/73
=> add lock/unlock app functionality

.github/workflows/checks.yml, genqlient.go, go.mod, go.sum
genqlient v0.7.0 was failing to run but upgrading to latest seems to work:
```
invalid schema: exceeded token limit of 15000
exit status 1
```
=> Upgrade genqlient to 4466fc10e4f3

volume_types.go
https://github.com/superfly/flyctl/pull/3972
=> Nomad is gone, remove machines only flag

Makefile, machine_types.go
Hope is to insert `Containers []*ContainerConfig` of into
https://github.com/superfly/flyctl/blob/f6a317fac815dcd70fb3d2ef9dd6e68a4a790296/internal/appconfig/config.go#L38
=> Prep for possible inclusion into fly.toml

flaps/actions.go, flaps/flaps_secrets.go, flaps/flapsaction_string.go, secrets_types.go
This supports the flaps machine api changes in https://github.com/superfly/nomad-firecracker/pull/3587
=> support machine api for updating app secrets in bulk and getting back updated min_vers.
